name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          - name: Fix Gradle Memory
  run: echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties

      - name: Build APK (light)
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sunil-apk
          path: app/build/outputs/apk/debug/app-debug.apk
